packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  valibot: ^1.4.0
loglevel: debug
ignoreScripts: true
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
pmOnFail: download
saveExact: true
savePrefix: ''
