name: "Chromatic Publish"

on:
  push:
    branches:
      - main
    paths:
      - "apps/storybook/**"
      - "packages/frey-ui/**"
      - "pnpm-lock.yaml"
      - "turbo.json"
      - ".github/workflows/chromatic.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          version: "11.3.0"
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24.16.0
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo run build-storybook --filter=@frey-ui/storybook
      - run: test -f apps/storybook/storybook-static/preview-stats.json
      - uses: chromaui/action@1bbb5819252d9782cb7d77122d9becae467def18 # v16.10.1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: apps/storybook
          storybookBuildDir: storybook-static
          onlyChanged: true
